// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductInvoice.Models;

#nullable disable

namespace ProductInvoice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220721094646_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductInvoice.Models.Discount", b =>
                {
                    b.Property<Guid>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DiscountCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiscountExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiscountId");

                    b.HasIndex("ProductId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("ProductInvoice.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvoiceCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ProductInvoice.Models.InvoiceItems", b =>
                {
                    b.Property<Guid>("InvoiceItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NoOfItems")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceItemsId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("ProductInvoice.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProductBasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("75373a09-95d7-4e03-b489-7f99a81ed3b8"),
                            ProductBasePrice = 9999m,
                            ProductCategory = "Mobiles",
                            ProductCreated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7659),
                            ProductName = "Novice",
                            ProductUpdated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7669)
                        },
                        new
                        {
                            ProductId = new Guid("333ae2c4-50c2-4f44-8499-35e06bce0c7e"),
                            ProductBasePrice = 49999m,
                            ProductCategory = "Television",
                            ProductCreated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7671),
                            ProductName = "Stans Pro",
                            ProductUpdated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7671)
                        },
                        new
                        {
                            ProductId = new Guid("c28a8af3-b1a2-4d87-83fd-64c36153d0bd"),
                            ProductBasePrice = 19999m,
                            ProductCategory = "Washing Machine",
                            ProductCreated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7673),
                            ProductName = "Ultra Washing",
                            ProductUpdated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7673)
                        },
                        new
                        {
                            ProductId = new Guid("e1ac9917-d9fe-4aea-a43e-5680580665da"),
                            ProductBasePrice = 59999m,
                            ProductCategory = "Air Conditioner",
                            ProductCreated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7674),
                            ProductName = "Cool Breeze",
                            ProductUpdated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7675)
                        },
                        new
                        {
                            ProductId = new Guid("b69b0f72-5162-4e38-867b-25c123b9f939"),
                            ProductBasePrice = 99999m,
                            ProductCategory = "Laptop",
                            ProductCreated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7676),
                            ProductName = "T14",
                            ProductUpdated = new DateTime(2022, 7, 21, 15, 16, 46, 114, DateTimeKind.Local).AddTicks(7677)
                        });
                });

            modelBuilder.Entity("ProductInvoice.Models.Discount", b =>
                {
                    b.HasOne("ProductInvoice.Models.Product", null)
                        .WithMany("discounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductInvoice.Models.InvoiceItems", b =>
                {
                    b.HasOne("ProductInvoice.Models.Invoice", null)
                        .WithMany("invoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductInvoice.Models.Product", null)
                        .WithMany("invoiceItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductInvoice.Models.Invoice", b =>
                {
                    b.Navigation("invoiceItems");
                });

            modelBuilder.Entity("ProductInvoice.Models.Product", b =>
                {
                    b.Navigation("discounts");

                    b.Navigation("invoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
